name: mati_plugin_flutter_example
description: Demonstrates how to use the mati_plugin_flutter .

publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fluttertoast: ^3.1.3

  mati_plugin_flutter:
    path: ../

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
